"""Deterministic builder for the review-only IW-001 structured pilot fixture."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]; OUT=ROOT/'data/international-watch/cases/IW-001'; OUT.mkdir(parents=True,exist_ok=True)
ASOF='2026-08-19T12:00:00Z'; SCHEMA='1.0.0'; REVIEW_AT='2026-08-19T15:00:00Z'; REVIEWER='Cognitive Logic — International Watch Methodology Review'
AUTHORIZED_AT='2026-08-20T19:17:12Z'; AUTHORIZED_BY='Roberto Malini'; AUTHORIZED_ROLE='Founder and Editor-in-Chief'; PUBLISHED_AT='2026-08-19T14:48:22Z'
def common(i,status='approved'):
 return {'id':i,'schema_version':SCHEMA,'record_version':'1.0.0','created_at':ASOF,'updated_at':REVIEW_AT,'valid_from':ASOF,'valid_until':None,'as_of':ASOF,'status':status,'supersedes':None,'provenance':{'created_by':'Cognitive Logic IW research','method':'Manual OSINT review; deterministic structuring','sources':[],'transformations':['Phase 3 formal methodological review']},'responsible_actor':'Cognitive Logic IW author','review_required':True,'review_due':'2026-09-19T12:00:00Z','content_hash':None}
def dump(name,records): (OUT/name).write_text(json.dumps({'schema_version':SCHEMA,'case_id':'IW-001','records':records},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

events=[]
for eid,typ,title,parent in [('IW-001','dossier','Iran / Stretto di Hormuz — monitoring case',None),('IW-001-E001','event','Stato del traffico marittimo','IW-001'),('IW-001-E002','event','Dichiarazioni incompatibili su apertura e chiusura','IW-001'),('IW-001-E003','event','Proposta Iran–Oman','IW-001'),('IW-001-E004','event','Incidente MINOAN DIGNITY — 17 agosto','IW-001'),('IW-001-E005','event','Incidente MINOAN PIONEER — 3 agosto','IW-001'),('IW-001-S001','snapshot','Snapshot 19 agosto 2026','IW-001')]:
 scope={'start':'2026-08-01T00:00:00Z','end':ASOF}; location='Strait of Hormuz / Gulf of Oman'
 if eid=='IW-001-E004': scope={'start':'2026-08-17T00:00:00Z','end':'2026-08-17T23:59:59Z'}; location='Strait of Hormuz'
 if eid=='IW-001-E005': scope={'start':'2026-08-03T00:00:00Z','end':'2026-08-03T23:59:59Z'}; location='20 NM northeast of Al Khasab, Oman'
 history=[{'at':ASOF,'actor':'Cognitive Logic IW author','change':'Initial Phase 2 research record'}]
 if eid in {'IW-001-E004','IW-001-E005'}: history.append({'at':'2026-08-19T14:23:40Z','actor':'Cognitive Logic IW author','change':'Identity reverified against IMO register current at 19 August; distinct incidents retained.'})
 r=common(eid); r.update(case_id='IW-001',event_id=eid,parent_event_id=parent,record_type=typ,title=title,description='Record di monitoraggio non pubblico; cut-off 12:00 UTC, with identity correction observed 14:23:40 UTC.',temporal_scope=scope,time_precision='day' if eid in {'IW-001-E004','IW-001-E005'} else 'range',locations=[{'name':location,'coordinates':None}],actors=['Iran','Oman','United States','commercial shipping'],related_claim_ids=[],related_event_ids=[],update_history=history); events.append(r)
dump('event-registry.json',events)

source_specs=[
('IW-001-SRC-001','IMO Middle East hub','https://www.imo.org/en/mediacentre/hottopics/pages/middle-east-strait-of-hormuz.aspx','primary','IMO',[]),
('IW-001-SRC-002','UKMTO/JMIC Update 079','https://www.ukmto.org/-/media/ukmto/products/update-079-jmic-advisory-note-02-august-1.pdf','primary','JMIC',[]),
('IW-001-SRC-003','JMIC Advisory 009-26','https://wwwcdn.imo.org/localresources/en/MediaCentre/HotTopics/Documents/JMIC%20Advisory%20Note%2000926%20SoH%20open.pdf','primary','JMIC',[]),
('IW-001-SRC-004','US MARAD Advisory 2026-004','https://www.maritime.dot.gov/msci/2026-004-persian-gulf-strait-hormuz-and-gulf-oman-iranian-attacks-commercial-vessels','primary','US MARAD',[]),
('IW-001-SRC-005','Iran MFA statement via Tasnim','https://tasnimnews.ir/en/news/2026/08/03/3662859/iran-denies-us-talks-limits-oman-negotiations-to-hormuz','mixed','Iran MFA',['IW-001-SRC-010']),
('IW-001-SRC-006','Iran FM statement via Anadolu','https://www.aa.com.tr/en/middle-east/iran-says-very-close-to-agreement-with-oman-on-new-hormuz-corridor/4021894','secondary','Anadolu',['IW-001-SRC-011']),
('IW-001-SRC-007','AP rolling report 18 August','https://apnews.com/article/iran-us-israel-lebanon-gaza-hormuz-august-18-2026-9c48af23b713709e8e170191fbc78c2a','secondary','Associated Press',['IW-001-SRC-012','IW-001-SRC-013']),
('IW-001-SRC-008','AP Oman/Iran report','https://apnews.com/article/oman-iran-war-us-hormuz-a8298715a51159225d2f37a6d50ce682','secondary','Associated Press',['IW-001-SRC-012']),
('IW-001-SRC-009','VesselFinder MINOAN DIGNITY','https://www.vesselfinder.com/vessels/details/9294484','secondary','VesselFinder',['IW-001-SRC-014']),
('IW-001-SRC-010','Iran MFA press conference','unavailable:original-not-inspected','primary','Iran MFA',[]),
('IW-001-SRC-011','IRNA report cited by Anadolu','unavailable:original-not-inspected','primary','IRNA',[]),
('IW-001-SRC-012','UKMTO incident report cited by AP','unavailable:original-item-not-located','primary','UKMTO',[]),
('IW-001-SRC-013','Kpler weekly crossing dataset cited by AP','unavailable:licensed-dataset-not-inspected','primary','Kpler',[]),
('IW-001-SRC-014','AIS feed surfaced by VesselFinder','unavailable:dynamic-licensed-feed','primary','AIS data providers',[])]
source_specs.append(('IW-001-SRC-015','IMO Highlighted (Confirmed) incidents — accessed 2026-08-19T14:23:40Z','https://www.imo.org/en/mediacentre/hottopics/pages/middle-east-highlighted-incidents.aspx','primary','IMO',[]))
sources=[]
published_at={'IW-001-SRC-002':'2026-08-02T00:00:00Z','IW-001-SRC-003':'2026-06-18T00:00:00Z','IW-001-SRC-005':'2026-08-03T11:45:00Z','IW-001-SRC-006':'2026-08-08T00:00:00Z','IW-001-SRC-007':'2026-08-18T08:20:03Z','IW-001-SRC-008':'2026-08-18T14:30:04Z'}
as_at={'IW-001-SRC-002':'2026-08-02T23:59:59Z','IW-001-SRC-003':'2026-06-18T23:59:59Z','IW-001-SRC-007':'2026-08-18T23:59:59Z','IW-001-SRC-008':'2026-08-18T23:59:59Z','IW-001-SRC-015':'2026-08-19T23:59:59Z'}
for sid,name,url,kind,entity,deps in source_specs:
 accessed='2026-08-19T14:23:40Z' if sid=='IW-001-SRC-015' else ASOF
 r=common(sid); unavailable=url.startswith('unavailable:'); r.update(source_id=sid,entity_id=entity,source_name=name,jurisdiction=['international'],source_role=['publisher'] if not deps else ['publisher','repeater'],ownership_or_control={'known':False,'description':'Not assessed beyond named publisher.'},primary_or_secondary=kind,party_to_event='unknown',access_mode='unavailable' if unavailable else 'open',language=['en'],publication_channel='web',originator_of=[],repeats=deps,derived_from=deps,known_method='Direct publication or explicitly identified derivative citation.',limitations=[url if unavailable else 'No full copyrighted copy archived; metadata and short analytic notes only. Unknown publication/source-as-at values remain null rather than inferred.'],identity_verification={'status':'verified' if not unavailable else 'unverified','basis':'Official domain or publisher page; inaccessible origins remain unverified.'},archived_capture=None,original_uri=None if unavailable else url,archived_unavailability_reason='No lawful archive captured during cut-off; dynamic/licensed or time constraint.',original_text_available=not unavailable,translation_trace=[],publication_timestamp=published_at.get(sid),source_as_at=as_at.get(sid),accessed_at=accessed); sources.append(r)
dump('source-registry.json',sources)

claims_data=[
('001','IW-001-E001','Tracked commercial vessels transited the Strait during the week ending 16 August 2026.','observable_fact','Kpler dataset as reported by AP','95 confirmed crossings; three on Sunday','PLAUSIBILE'),
('002','IW-001-E001','The observed weekly count was 95 confirmed crossings, down 19.5%.','observable_fact','Kpler dataset as reported by AP','95 crossings under Kpler method','PLAUSIBILE'),
('003','IW-001-E001','AIS-derived counts do not represent all physical traffic.','inference','Cognitive Logic analysis','tracked traffic is not total traffic','ACCERTATO'),
('004','IW-001-E001','At least some commercial vessels could physically navigate the Strait in the observed period.','inference','Cognitive Logic analysis','physical navigability for observed vessels','PLAUSIBILE'),
('005','IW-001-E001','Normal commercial freedom of navigation existed at the cut-off.','inference','No single origin','normal unrestricted commercial passage','CONTRADDETTO'),
('006','IW-001-E002','The US President stated the Strait was open and operating.','statement','US President as reported by AP','statement was made','ACCERTATO'),
('007','IW-001-E002','The Strait was open and operating in the normal-commercial sense.','statement','US President as reported by AP','normal commercial opening','CONTESTATO'),
('008','IW-001-E002','Iran stated no change should be expected until US conditions were met.','statement','Iran MFA as carried by Tasnim','conditional non-reopening position','ACCERTATO'),
('009','IW-001-E002','Iran exercised comprehensive operational control over every transit.','statement','Iranian claims reported in derivatives','comprehensive operational control','NON_VERIFICATO'),
('010','IW-001-E002','Iran possessed exclusive legal control or sovereignty over the Strait.','statement','Iranian/derivative framing','exclusive legal control','CONTRADDETTO'),
('011','IW-001-E003','Iran and Oman were negotiating a temporary shipping arrangement.','statement','Iran MFA/FM statements','bilateral negotiation existed','FORTEMENTE_CORROBORATO'),
('012','IW-001-E003','A definitive Iran–Oman agreement had been published by the cut-off.','observable_fact','No identified publication','published definitive agreement','NON_VERIFICATO'),
('013','IW-001-E004','MINOAN DIGNITY (IMO 9294484) was damaged in the Strait of Hormuz on 17 August; one seafarer died and no pollution was reported.','observable_fact','IMO updated incident register','incident identity, date, damage, fatality and no reported pollution','ACCERTATO'),
('014','IW-001-E005','MINOAN PIONEER (IMO 9471630) was damaged 20 NM northeast of Al Khasab on 3 August; one seafarer was missing and pollution was unconfirmed.','observable_fact','IMO updated incident register','distinct incident identity, location, damage, missing seafarer and pollution status','ACCERTATO'),
('015','IW-001-E005','The actor responsible for the 3 August MINOAN PIONEER strike was established.','inference','No authenticated attribution','MINOAN PIONEER attack attribution','INDETERMINABILE'),
('016','IW-001-E001','Maritime security risk remained elevated at the cut-off.','inference','MARAD and incident reporting','elevated risk','FORTEMENTE_CORROBORATO'),
('017','IW-001-E001','The disruption caused directly quantifiable energy consequences at cut-off.','inference','General reporting','specific causal energy consequence','INDETERMINABILE'),
('018','IW-001-E004','The actor responsible for the 17 August MINOAN DIGNITY incident was established.','inference','No authenticated attribution','MINOAN DIGNITY attack attribution','INDETERMINABILE')]
claims=[]; evidence=[]; assessments=[]
for n,eid,text,ctype,origin,obj,state in claims_data:
 cid=f'IW-001-CLM-{n}'; sid='IW-001-SRC-007';
 if n in {'008'}: sid='IW-001-SRC-005'
 if n in {'011'}: sid='IW-001-SRC-006'
 if n in {'013','014'}: sid='IW-001-SRC-015'
 if n in {'016'}: sid='IW-001-SRC-004'
 evid=f'IW-001-EVD-{n}'; aid=f'IW-001-ASM-{n}'
 counter=[] if state not in {'CONTESTATO','CONTRADDETTO'} else [evid]
 r=common(cid); r.update(claim_id=cid,event_id=eid,claim_text_original=text,language='en',translation=text,translation_method='human',claim_type=ctype,speaker_actor_id=origin,origin_source_id=sid,origin_timestamp=None,publication_timestamp=None,original_context='Analytic atom; statement content kept distinct from statement occurrence.',subject=origin,predicate='asserts or establishes',object=obj,qualifiers=['as_of 2026-08-19T12:00:00Z'],geographic_scope=['Strait of Hormuz'],temporal_scope={'start':'2026-08-01T00:00:00Z','end':ASOF},definition_refs=['CONTROLLED-GLOSSARY'],testability={'status':'partially_testable','method':'Inspect named origin and claim-specific evidence; preserve AIS and access limits.'},evidence_refs=[evid],counter_evidence_refs=counter,counter_evidence_absence_reason=None if counter else 'No claim-specific counter-evidence identified at cut-off; absence is not confirmation.',dependency_refs=[],assessment_id=aid,revision_triggers=['new material evidence','source correction or withdrawal','dependency or temporal-scope change']); claims.append(r)
 ev=common(evid); ev.update(evidence_id=evid,evidence_type='documentary_or_analytic_record',description=f'Evidence note for {cid}',producer=origin,collector='Cognitive Logic IW author',custodian='Cognitive Logic',capture_time=ASOF,event_time=None,location='Strait of Hormuz',original_uri=next((x[2] for x in source_specs if x[0]==sid and not x[2].startswith('unavailable:')),None),archived_uri=None,archived_unavailability_reason='No lawful local archive captured; URL and access time retained.',metadata_preserved=True,chain_of_custody=[{'actor':'Cognitive Logic IW author','action':'inspected source and recorded bounded note','at':ASOF}],authentication_status='partially_authenticated',independence_from_claimant='unknown',coverage=obj,completeness='Claim-specific excerpt/metadata; not a complete copyrighted work.',resolution='Textual reporting or structured incident listing.',verifiability='Reinspect the linked page and upstream origin where accessible.',recency='Current or identified historical material as of cut-off.',proximity_to_event='Varies; derivative sources retain upstream dependency.',known_transformations=['English source or human analytic normalization'],technical_limitations=['AIS-off, spoofing, jamming, latency and coverage may affect traffic claims'],limitations=['Statement evidence does not establish statement content.'],probative_value=[{'claim_id':cid,'establishes':obj if state in {'ACCERTATO','FORTEMENTE_CORROBORATO'} else 'Limited support or contradiction within stated scope.'}],supports=[cid] if state not in {'CONTRADDETTO'} else [],contradicts=[cid] if state=='CONTRADDETTO' else [],does_not_establish=['Any broader condition outside temporal and definitional scope','Sovereignty or legal control unless expressly identified','Causal attribution without separate evidence']); evidence.append(ev)
 a=common(aid); a.update(assessment_id=aid,claim_id=cid,state=state,state_definition_version=SCHEMA,reasoning_summary=('NON DETERMINABILE CON LE EVIDENZE DISPONIBILI: ' if state=='INDETERMINABILE' else '')+f'Assigned claim-specifically from inspected material; {origin}; dependencies and scope limit generalization.',supporting_evidence=[evid] if state!='CONTRADDETTO' else [],contrary_evidence=[evid] if state=='CONTRADDETTO' else [],independent_evidence_groups=[{'group_id':f'IW-001-GRP-{n}','evidence_ids':[evid],'independence_basis':'Single identified evidentiary origin; derivatives are not additional groups.'}],unresolved_contradictions=['IW-001-CON-001'] if n in {'005','007','008'} else [],scope={'geographic':['Strait of Hormuz'],'temporal':{'start':'2026-08-01T00:00:00Z','end':ASOF},'definitions':['Controlled glossary distinctions apply.']},unknowns=['Unobserved or dark traffic','Unpublished diplomatic terms','Attribution where not authenticated'],limits=['Cut-off 12:00 UTC','Dynamic pages and inaccessible upstream material','No inference from URL count'],decision_rules_applied=[{'ACCERTATO':'ES-ACC-1','FORTEMENTE_CORROBORATO':'ES-FC-1','PLAUSIBILE':'ES-PLA-1','CONTESTATO':'ES-CON-1','NON_VERIFICATO':'ES-NV-1','CONTRADDETTO':'ES-CTR-1','INDETERMINABILE':'ES-IND-1'}[state],'republication-is-not-independent-corroboration'],excluded_evidence=[],reviewer=REVIEWER,previous_assessment=None,change_reason='Phase 3 formal review confirmed the claim-specific state without homogenization.'); assessments.append(a)
dump('claim-registry.json',claims); dump('evidence-ledger.json',evidence); dump('epistemic-assessment.json',assessments)

deps=[]
for i,(frm,to,typ) in enumerate([('IW-001-SRC-005','IW-001-SRC-010','repeats'),('IW-001-SRC-006','IW-001-SRC-011','repeats'),('IW-001-SRC-007','IW-001-SRC-012','uses_statement'),('IW-001-SRC-007','IW-001-SRC-013','uses_dataset'),('IW-001-SRC-009','IW-001-SRC-014','uses_dataset')],1):
 d=common(f'IW-001-DEP-{i:03d}'); d.update(node_id=frm,node_type='source',edge_id=f'IW-001-DEP-{i:03d}',edge_type=typ,**{'from':frm,'to':to},shared_origin_id=to,evidence_collection_independent='no',organizationally_independent='unknown',ownership_independent='unknown',methodologically_independent='no',shared_dataset='yes' if typ=='uses_dataset' else 'no',shared_agency='no',shared_statement='yes' if typ in {'repeats','uses_statement'} else 'no',republication_or_translation=typ=='repeats',dependency_basis=['Downstream source explicitly attributes the relevant statement or data to upstream origin.'],dependency_status='dependent',unknown_dependency=False,counts_as_independent_corroboration=False); deps.append(d)
dump('source-dependency.json',deps)

c=common('IW-001-CON-001'); c.update(contradiction_id='IW-001-CON-001',claim_a='IW-001-CLM-007',claim_b='IW-001-CLM-008',subject='Strait operating condition',predicate='is open versus remains conditionally restricted',object='commercial passage',definition='US open-and-operating wording versus Iranian non-reopening condition; not fully coextensive',temporal_scope={'start':'2026-08-18T00:00:00Z','end':ASOF},place='Strait of Hormuz',qualifiers=['traffic present but sharply reduced','different definitions likely'],incompatibility='Normal-commercial openness is incompatible with a claimed conditional non-reopening, but physical transit can coexist with both.',extent='partial',definition_divergence_possible=True,resolution_evidence_needed=['Published operational rules','route-neutral traffic data','authenticated Iran–Oman text']); dump('contradictions.json',[c])

n=common('IW-001-NAR-001'); n.update(comparison_id='IW-001-NAR-001',event_id='IW-001-E002',source_document_id='IW-001-SRC-007',compared_document_ids=['IW-001-SRC-005','IW-001-SRC-006','IW-001-SRC-008'],headline='Open/closed/control language across US, Iranian, regional and agency reporting',lead='Comparison of observable attribution, modality and context.',claims_included=['IW-001-CLM-006','IW-001-CLM-008','IW-001-CLM-011'],claims_omitted=['No inspected Omani original statement'],actor_labels=['US President','Iran MFA','Iran FM','regional officials'],agency_assignment=['US narrative assigns operating status','Iranian narrative assigns conditions to US conduct','AP attributes negotiation details to anonymous regional officials'],certainty_markers=['remains','will not','very close'],evaluative_language=[],quotation_changes=['Derivative translations may normalize Persian wording'],quantifier_changes=[],modality_changes=['near agreement is not final agreement'],temporal_generalization=['weekly traffic data cannot establish conditions at every instant'],context_loss=['headlines using open may omit physical/formal/normal distinction'],headline_body_divergence=['Agency body qualifies limited traffic despite open-and-operating statement'],observable_transformations=[{'type':'statement_to_fact','source_segment':'Trump insisted the Strait remains open and operating','compared_segment':'Strait open','description':'Attribution can disappear in derivative headlines.'},{'type':'context_loss','source_segment':'95 Kpler-confirmed crossings under a dataset method','compared_segment':'traffic continues','description':'Method and limited coverage can disappear.'}],analyst_notes=['No intent classification; AP is not independent of Kpler or UKMTO for those facts.']); dump('narrative-comparison.json',[n])

w=common('IW-001-WF-001','approved'); w['updated_at']=AUTHORIZED_AT; w.update(workflow_id='IW-001-WF-001',record_id='IW-001',current_state='published',history=[{'from':None,'to':'draft','at':ASOF,'actor':'Cognitive Logic IW author','role':'author','reason':'Created pilot.'},{'from':'draft','to':'in_review','at':ASOF,'actor':'Cognitive Logic IW author','role':'author','reason':'Submitted for formal review; no publication authorization.'},{'from':'in_review','to':'approved','at':REVIEW_AT,'actor':REVIEWER,'role':'Codex-assisted technical and methodological review function','reason':'All Phase 3 methodological, structural, temporal and validation gates passed. IW-001 is approved methodologically; final organizational approval remains reserved to the human responsible officer of Cognitive Logic. No external certification or specialist legal review.'},{'from':'approved','to':'published','at':AUTHORIZED_AT,'actor':AUTHORIZED_BY,'role':AUTHORIZED_ROLE,'reason':'Prospective human authorization for publication and continued public availability of IW-001. The technical publication predates this authorization: GitHub Pages deployment run 32266168273 completed successfully at 2026-08-19T14:48:22Z; this event does not represent the authorization as retroactive.'}],author='Cognitive Logic IW author',human_reviewer=REVIEWER,publication_automatic=False,reopen_conditions=['new material evidence','source correction or withdrawal','dependency discovered','scope or definition change'],new_evidence_policy='Return to in_review; create a versioned assessment and preserve history.',correction_policy='Non-material patch; material correction creates a superseding record.'); dump('workflow.json',[w])

manifest={'case_id':'IW-001','title':'Iran / Strait of Hormuz — 19 August 2026','schema_version':SCHEMA,'record_version':'1.0.0','status':'published','approved_at':REVIEW_AT,'authorized_at':AUTHORIZED_AT,'authorized_by':AUTHORIZED_BY,'authorized_role':AUTHORIZED_ROLE,'published_at':PUBLISHED_AT,'publication_evidence':'GitHub Pages deployment run 32266168273 for commit edca2db357a1b77d4bba722bc6f6564177cb1180; completed successfully at 2026-08-19T14:48:22Z.','reviewer':REVIEWER,'review_mode':'Technical and methodological review assisted by Codex','final_approval_reserved_to':'Roberto Malini — Founder and Editor-in-Chief','organizational_independence':False,'external_certification':False,'specialist_legal_review':False,'personal_reviewer_or_signature':None,'approval_scope':'Methodological conformity approved 2026-08-19; publication and continued public availability authorized prospectively on 2026-08-20. No external certification or source endorsement.','authorization_scope':'publication and continued public availability of IW-001','cut_off':ASOF,'publication_allowed':True,'article_url':'https://cognitivelogic.it/international-watch/hormuz-aperto-cosa-sappiamo/','dossier_url':'https://cognitivelogic.it/international-watch/iw-001-iran-stretto-hormuz/','public_epistemic_outcome':'PARZIALMENTE VERIFICATA','files':['event-registry.json','claim-registry.json','source-registry.json','evidence-ledger.json','source-dependency.json','narrative-comparison.json','epistemic-assessment.json','contradictions.json','workflow.json','dossier-manifest.json'],'identity_verification':'IMO register current at 19 August confirms distinct MINOAN DIGNITY (17 August) and MINOAN PIONEER (3 August) incidents.','verification_accessed_at':'2026-08-19T14:23:40Z','source_page_as_at':'2026-08-19','local_evidence_files':[],'missing_local_file_reason':'No copyrighted source copies archived; URLs, timestamps and bounded notes retained.','methodological_note':'Progressively updated sources supersede incomplete earlier snapshots for later events; an earlier source does not contradict a later update merely by omission.'}
(OUT/'dossier-manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
