#!/usr/bin/env python3
"""Build the human-approved and published IW-003 canonical bundle."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/international-watch/cases/IW-003"
NOW = "2026-08-20T12:00:00Z"
CUT = "2026-08-20T21:59:59Z"
DUE = "2026-11-20T21:59:59Z"
REVIEWER = "Cognitive Logic — International Watch Methodology Review"
APPROVED = "2026-08-20T12:30:00Z"

def common(identifier, sources=()):
    return {"id":identifier,"schema_version":"1.0.0","record_version":"1.0.0","created_at":NOW,
      "updated_at":APPROVED,"valid_from":NOW,"valid_until":None,"as_of":CUT,"status":"approved",
      "supersedes":None,"provenance":{"created_by":"Cognitive Logic IW author assisted by Codex",
      "method":"DFV-002 and QEN International Watch manual source review; Codex-assisted structuring",
      "sources":list(sources),"transformations":["Claim-bounded Italian synthesis; no truth or trust score"]},
      "responsible_actor":"Cognitive Logic IW author","review_required":True,"review_due":DUE,"content_hash":None}

sources = [
 ("001","Ordinanza della Corte (Settima Sezione), 10 luglio 2026, C-574/25","Court of Justice of the European Union","EU","primary","no","en","2026-07-10T00:00:00Z","https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX%3A62025CO0574","Decisione giudiziaria primaria; dispositivo e motivazione","Stabilisce interpretazioni di diritto UE nel perimetro deciso; non accerta la scarsità italiana."),
 ("002","Direttiva 2006/123/CE relativa ai servizi nel mercato interno","European Parliament and Council","EU","primary","no","en","2006-12-27T00:00:00Z","https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX%3A32006L0123","Norma primaria, articolo 12","Definisce la condizione e la procedura; non misura la scarsità in un territorio."),
 ("003","Promoimpresa, cause riunite C-458/14 e C-67/15","Court of Justice of the European Union","EU","primary","no","en","2016-07-14T00:00:00Z","https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX%3A62014CJ0458","Precedente giudiziario sulla scarsità e selezione","Non decide la scarsità di ogni costa italiana al cut-off."),
 ("004","Comune di Ginosa, C-348/22","Court of Justice of the European Union","EU","primary","no","en","2023-04-20T00:00:00Z","https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX%3A62022CJ0348","Precedente su criteri, effetto diretto e autorità amministrative","Non convalida automaticamente la nota italiana del 2023."),
 ("005","Società Italiana Imprese Balneari, C-598/22","Court of Justice of the European Union","EU","primary","no","en","2024-07-11T00:00:00Z","https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A62022CJ0598","Precedente su scadenza, rinnovo e opere non amovibili","Il suo oggetto principale non è una mappatura nazionale della scarsità."),
 ("006","Decreto-legge 16 settembre 2024 n. 131, testo coordinato","Italian Republic — Gazzetta Ufficiale","IT","primary","yes","it","2024-11-14T00:00:00Z","https://www.gazzettaufficiale.it/atto/serie_generale/caricaArticoloDefault/originario?atto.codiceRedazionale=24A06077&atto.dataPubblicazioneGazzetta=2024-11-14&atto.tipoProvvedimento=TESTO+COORDINATO+DEL+DECRETO-LEGGE","Normativa italiana vigente sulle procedure e scadenze","Non prova da sola la compatibilità di ogni applicazione concreta con il diritto UE."),
 ("007","Risposta della Commissione E-003631/2023 su INFR(2020)4118","European Commission via European Parliament","EU","primary","yes","it","2024-03-26T00:00:00Z","https://www.europarl.europa.eu/doceo/document/E-9-2023-003631-ASW_IT.html","Posizione istituzionale sulla valutazione effettiva, obiettiva e qualitativa","Non è una sentenza e non contiene il testo integrale del parere motivato."),
 ("008","Nota della Presidenza del Consiglio del 6 ottobre 2023","Presidenza del Consiglio dei ministri","IT","primary","yes","it","2023-10-06T00:00:00Z",None,"Atto nazionale richiamato dall'ordinanza C-574/25","Testo ufficiale integrale non reperito nel perimetro; competenza, vincolatività e metodo restano da verificare dal giudice nazionale."),
 ("009","Concessioni balneari in Emilia-Romagna","Coste360","IT","secondary","no","it",None,"https://www.coste360.it/concessioni-balneari/emilia-romagna","Contesto territoriale su atti e distribuzione","Non è fonte giuridica e non dimostra scarsità o non scarsità; non distingue da sola costa balneabile, concedibile ed economicamente utilizzabile."),
 ("010","I Balneari hanno vinto: nessun obbligo di gare pubbliche","Panorama, ripubblicato da TuttiQuotidiani","IT","secondary","no","it","2026-07-24T00:00:00Z","https://tuttiquotidiani.it/it/news/i-balneari-hanno-vinto-per-la-corte-di-giustizia-ue-nessun-obbligo-di-gare-pubbliche","Esempio documentato di trasformazione narrativa","Ripubblicazione non indipendente; titolo e sintesi non modificano il dispositivo della Corte."),
 ("011","Caso 901/2026/LA su INFR(2020)4118","European Ombudsman","EU","primary","no","it","2026-06-17T00:00:00Z","https://www.ombudsman.europa.eu/it/opening-summary/it/227729","Conferma istituzionale che un'indagine sulla gestione della procedura è aperta","Non decide il merito della scarsità o la validità delle proroghe."),
 ("012","Terracina mette a gara 86 concessioni balneari","Coste360 — Osservatorio","IT","secondary","no","it","2026-06-06T00:00:00Z","https://osservatorio.coste360.it/2026/06/06/terracina-mette-a-gara-86-concessioni-balneari-indennizzi-riconosciuti-con-tetto-provvisorio-di-100-000-e-e-perizie-a-carico-degli-uscenti/","Ricostruzione giornalistica verticale di una procedura comunale e del trattamento provvisorio degli indennizzi","Fonte editoriale secondaria: non sostituisce gli atti originari, non prova la legittimità della procedura e non stabilisce criteri normativi."),
 ("013","Laigueglia indice la gara per 45 concessioni demaniali marittime","Coste360 — Osservatorio","IT","secondary","no","it","2026-05-16T00:00:00Z","https://osservatorio.coste360.it/2026/05/16/laigueglia-indice-la-gara-per-45-concessioni-demaniali-marittime/","Ricostruzione giornalistica verticale di una procedura comunale e dell'esclusione degli indennizzi","Fonte editoriale secondaria: non sostituisce gli atti originari, non prova la legittimità della procedura e non stabilisce criteri normativi."),
]

src_records=[]
for n,title,entity,jur,kind,party,lang,pub,url,method,limit in sources:
 i=f"IW-003-SRC-{n}"; r=common(i)
 r.update({"source_id":i,"entity_id":entity,"source_name":title,"jurisdiction":[jur],"source_role":["publisher","originator"],
  "ownership_or_control":{"known":True,"description":entity},"primary_or_secondary":kind,"party_to_event":party,"access_mode":"open" if url else "unavailable",
  "language":[lang],"publication_channel":"official web publication" if kind=="primary" else "web publication",
  "originator_of":[],"repeats":[],"derived_from":[],"known_method":method,"limitations":[limit,"Autorevolezza o autenticità non equivalgono a verità sostanziale."],
  "identity_verification":{"status":"verified","basis":"Identità e canale verificati; per SRC-008 è verificata l'esistenza tramite la decisione giudiziaria, non il testo integrale."},
  "archived_capture":None,"original_uri":url,"archived_unavailability_reason":"Nessuna copia locale archiviata; URL, accesso e nota probatoria delimitata conservati." if url else "Documento integrale non reperito su un canale ufficiale accessibile al cut-off.",
  "original_text_available":bool(url),"translation_trace":["Sintesi italiana redazionale"] if lang=="en" else [],"publication_timestamp":pub,"source_as_at":pub,"accessed_at":NOW})
 src_records.append(r)

claims = [
 ("001","La decisione della Corte di giustizia UE del 10 luglio 2026 consente all'Italia di evitare le gare per le concessioni balneari.","interpretation","001","Corte UE","consente","all'Italia di evitare in generale le gare","CONTRADDETTO",["001","002","004"],["001","002","004"],"E001"),
 ("002","Le concessioni demaniali marittime turistico-ricreative descritte dalla Corte sono autorizzazioni ai sensi della direttiva 2006/123.","observable_fact","001","concessioni demaniali descritte","rientrano","nel regime delle autorizzazioni della direttiva 2006/123","ACCERTATO",["001","003","004"],[],"E001"),
 ("003","Le concessioni descritte non sono concessioni di servizi quando l'autorità fissa solo condizioni generali e non procura servizi specifici.","observable_fact","001","concessioni descritte","non sono","concessioni di servizi ex direttiva 2014/23","ACCERTATO",["001"],[],"E001"),
 ("004","Se la scarsità limita le autorizzazioni, l'articolo 12 impone una selezione imparziale e trasparente.","observable_fact","002","articolo 12","impone","selezione in presenza di scarsità limitante","ACCERTATO",["001","002","003","004"],[],"E002"),
 ("005","L'articolo 12 vieta sia il rinnovo automatico sia l'estensione automatica.","observable_fact","001","articolo 12","vieta","rinnovo ed estensione automatici","ACCERTATO",["001","002","004"],[],"E002"),
 ("006","La continuità del rapporto è ammessa solo per il tempo strettamente necessario quando una procedura è già stata avviata.","observable_fact","006","legge italiana vigente","ammette","continuità strettamente necessaria dopo avvio procedura","ACCERTATO",["006"],[],"E003"),
 ("007","La scarsità può essere valutata con approccio nazionale, locale o combinato, usando criteri obiettivi, trasparenti, proporzionati e non discriminatori.","observable_fact","001","autorità competente","può valutare","scarsità con approcci e criteri qualificati","ACCERTATO",["001","004","007"],[],"E002"),
 ("008","La nota italiana del 6 ottobre 2023 accerta in modo vincolante la non scarsità per tutta Italia.","interpretation","008","nota del 6 ottobre 2023","accerta in modo vincolante","non scarsità nazionale","INDETERMINABILE",["001","008"],["001","007"],"E003"),
 ("009","Le concessioni anteriori al 28 dicembre 2009 restano fuori dalla direttiva anche se successivamente rinnovate o prorogate.","interpretation","010","concessioni pre-2009","restano fuori","dalla direttiva dopo rinnovo o proroga","CONTRADDETTO",["001","004","005"],["001"],"E004"),
 ("010","Al cut-off le procedure italiane devono essere avviate entro il 30 giugno 2027 e i titoli proseguono fino al 30 settembre 2027, salvo differimento motivato non oltre il 31 marzo 2028.","observable_fact","006","normativa italiana","stabilisce","scadenze procedurali e transitorie","ACCERTATO",["006"],[],"E003"),
 ("011","I chilometri totali o balneabili, da soli, dimostrano la non scarsità delle aree economicamente utilizzabili.","inference","010","chilometri di costa","dimostrano da soli","non scarsità","CONTRADDETTO",["001","007","009"],["001","007"],"E005"),
 ("012","Il confronto con Spagna, Portogallo, Grecia e Francia prova che l'Italia può evitare le selezioni.","inference","010","confronto internazionale","prova","facoltà italiana di evitare selezioni","INDETERMINABILE",["002","006"],[],"E005"),
]

evmap={"001":"001","002":"002","003":"003","004":"004","005":"005","006":"006","007":"007","008":"008","009":"001","010":"006","011":"009","012":"002"}
clm_records=[]; asm_records=[]
for n,text_,ctype,origin,sub,pred,obj,state,support,contrary,event in claims:
 cid=f"IW-003-CLM-{n}"; aid=f"IW-003-ASM-{n}"; evid=[f"IW-003-EVD-{x}" for x in support]; counter=[f"IW-003-EVD-{x}" for x in contrary]
 r=common(cid,[f"IW-003-SRC-{origin}"]); r.update({"claim_id":cid,"event_id":f"IW-003-{event}","claim_text_original":text_,"language":"it","translation":None,"translation_method":"none","claim_type":ctype,
  "speaker_actor_id":None,"origin_source_id":f"IW-003-SRC-{origin}","origin_timestamp":None,"publication_timestamp":None,"original_context":"Claim atomizzato per IW-003.","subject":sub,"predicate":pred,"object":obj,"qualifiers":["scope Italia","as_of 20 agosto 2026"],"geographic_scope":["Italia","Unione europea"],
  "temporal_scope":{"start":"2006-12-27T00:00:00Z","end":CUT},"definition_refs":["METHODOLOGY.md","EPISTEMIC-TAXONOMY.md"],"testability":{"status":"testable" if state!="INDETERMINABILE" else "partially_testable","method":"Confronto con testo normativo, dispositivo, motivazione e atti ufficiali."},
  "evidence_refs":evid,"counter_evidence_refs":counter,"counter_evidence_absence_reason":None if counter else "Nessuna controevidenza comparabile individuata; revisione obbligatoria su nuova evidenza.","dependency_refs":[],"assessment_id":aid,"revision_triggers":["nuova decisione giudiziaria","modifica normativa","atto competente sulla scarsità","nuovi dati territoriali verificabili"]}); clm_records.append(r)
 a=common(aid,evid+counter); a.update({"assessment_id":aid,"claim_id":cid,"state":state,"state_definition_version":"1.0.0","reasoning_summary":({
  "001":"Il claim generalizza oltre il dispositivo: la Corte conserva la condizione di scarsità, il controllo nazionale e vieta automatismi.","008":"La Corte ordina al giudice nazionale di verificare competenza, criteri, vincolatività e possibile scostamento comunale; il testo integrale della nota non è disponibile.","009":"Il punto 2 del dispositivo dichiara irrilevante la data originaria quando intervengono rinnovi o proroghe.","011":"La Corte richiede una situazione fattuale e criteri qualificati; costa totale, balneabile, concedibile ed economicamente sfruttabile non coincidono.","012":"Regimi, titoli, durata e geografia degli altri Stati non sono omogenei e non derogano alla verifica italiana."}.get(n,"Il contenuto è direttamente delimitato da fonti normative o giudiziarie primarie entro lo scope indicato.")),
  "supporting_evidence":evid,"contrary_evidence":counter,"independent_evidence_groups":[{"group_id":f"IW-003-GRP-{n}","evidence_ids":evid,"independence_basis":"Gruppo primario delimitato; documenti della stessa catena giuridica non sono contati come conferme indipendenti."}],"unresolved_contradictions":[],
  "scope":{"geographic":["Italia","Unione europea"],"temporal":{"start":"2006-12-27T00:00:00Z","end":CUT},"definitions":["gare = procedura di selezione imparziale e trasparente","scarsità = limitazione fattuale delle autorizzazioni disponibili"]},
  "unknowns":["Counter-evidence search: nessuna controevidenza comparabile oltre quella registrata; attribuzione e applicazione concreta possono mutare.","Non è disponibile un accertamento giudiziario definitivo della scarsità per ogni territorio italiano."],"limits":["Nessuna revisione legale specialistica.","Cut-off 20 agosto 2026; dossier locale in review."],
  "decision_rules_applied":["ES-"+("ACC-1" if state=="ACCERTATO" else "CON-1" if state in ("CONTRADDETTO","CONTESTATO") else "IND-1")],"excluded_evidence":[],"reviewer":REVIEWER,"previous_assessment":None,"change_reason":"Prima valutazione IW-003, approvata e autorizzata alla pubblicazione dal responsabile umano."}); asm_records.append(a)

ev_records=[]
for n,title,entity,jur,kind,party,lang,pub,url,method,limit in sources:
 eid=f"IW-003-EVD-{n}"; related=[f"IW-003-CLM-{x[0]}" for x in claims if n in x[7] or n in x[8]]
 r=common(eid,[f"IW-003-SRC-{n}"]); r.update({"evidence_id":eid,"evidence_type":"public_document_or_bounded_analytic_record","description":title,"producer":entity,"collector":"Cognitive Logic IW author assisted by Codex","custodian":entity,
  "capture_time":NOW,"event_time":pub,"location":jur,"original_uri":url,"archived_uri":None,"archived_unavailability_reason":"Nessuna copia locale archiviata; URL e metadati registrati." if url else "Testo integrale non reperito su canale ufficiale accessibile.","metadata_preserved":True,
  "chain_of_custody":[{"actor":"Cognitive Logic IW author assisted by Codex","action":"Consultazione e sintesi probatoria delimitata.","at":NOW}],"authentication_status":"partially_authenticated" if not url else "authenticated","independence_from_claimant":"no" if party=="yes" else "yes",
  "coverage":method,"completeness":"Documento integrale accessibile via URL." if url else "Solo esistenza e descrizione mediate da fonti giudiziarie ufficiali.","resolution":"Documento","verifiability":"Ricontrollare URL e passaggi citati.","recency":"Valutata al cut-off.","proximity_to_event":"Diretta per atto o pubblicazione; contestuale per fonti secondarie.","known_transformations":["Sintesi italiana"],"technical_limitations":["Le pagine dinamiche possono cambiare."],"limitations":[limit],
  "probative_value":[{"claim_id":c,"establishes":"Supporto o controevidenza delimitati secondo claim e scope."} for c in related],"supports":related,"contradicts":[],"does_not_establish":[limit,"Intenzioni degli attori","Conclusioni oltre lo scope del documento"]}); ev_records.append(r)

events=[]
event_defs=[("IW-003","dossier",None,"Bolkestein e spiagge: la Corte UE ha davvero eliminato l'obbligo delle gare?",[c[0] for c in claims]),
 ("IW-003-E001","event","IW-003","Ordinanza C-574/25 del 10 luglio 2026",["001","002","003"]),("IW-003-E002","event","IW-003","Regime UE di scarsità e selezione",["004","005","007"]),
 ("IW-003-E003","event","IW-003","Nota italiana, normativa e scadenze",["006","008","010"]),("IW-003-E004","sub_event","IW-003-E001","Trattamento dei titoli anteriori al 2009",["009"]),("IW-003-E005","snapshot","IW-003","Dati territoriali e narrazioni al cut-off",["011","012"])]
for eid,typ,parent,title,nums in event_defs:
 r=common(eid); r.update({"case_id":"IW-003","event_id":eid,"parent_event_id":parent,"record_type":typ,"title":title,"description":"Unità governata IW-003; distingue diritto, accertamento fattuale, dichiarazioni e contesto territoriale.","temporal_scope":{"start":"2006-12-27T00:00:00Z","end":CUT},"time_precision":"range","locations":[{"name":"Italia e Unione europea","coordinates":None}],"actors":["Court of Justice of the European Union","Italian competent authorities","municipalities","beach operators","coastal communities"],"related_claim_ids":[f"IW-003-CLM-{n}" for n in nums],"related_event_ids":[],"update_history":[{"at":NOW,"actor":"Cognitive Logic IW author assisted by Codex","change":"Creato e sottoposto a revisione metodologica umana."}]}); events.append(r)

deps=[]
for n,frm,to,etype,basis in [("001","IW-003-SRC-010","IW-003-SRC-001","summary","Titolo giornalistico interpreta l'ordinanza."),("002","IW-003-SRC-001","IW-003-SRC-004","uses_evidence","L'ordinanza richiama Ginosa."),("003","IW-003-SRC-001","IW-003-SRC-003","uses_evidence","L'ordinanza richiama Promoimpresa."),("004","IW-003-SRC-001","IW-003-SRC-005","uses_evidence","L'ordinanza richiama SIIB."),("005","IW-003-SRC-008","IW-003-SRC-001","possible_dependency","La nota è descritta nell'ordinanza; testo integrale non acquisito."),("006","IW-003-SRC-009","IW-003-SRC-006","independent_collection","Dati territoriali distinti dalla fonte normativa."),("007","IW-003-SRC-012","IW-003-SRC-006","independent_collection","Ricostruzione editoriale di una procedura locale, distinta dalla fonte normativa nazionale."),("008","IW-003-SRC-013","IW-003-SRC-006","independent_collection","Ricostruzione editoriale di una procedura locale, distinta dalla fonte normativa nazionale.")]:
 i=f"IW-003-DEP-{n}"; dependent=etype!="independent_collection"; r=common(i,[frm,to]); r.update({"node_id":frm,"node_type":"source","edge_id":i,"edge_type":etype,"from":frm,"to":to,"shared_origin_id":to if dependent else None,"evidence_collection_independent":"no" if dependent else "yes","organizationally_independent":"yes","ownership_independent":"yes","methodologically_independent":"no" if dependent else "yes","shared_dataset":"unknown" if dependent else "no","shared_agency":"no","shared_statement":"yes" if dependent else "no","republication_or_translation":etype=="summary","dependency_basis":[basis],"dependency_status":"dependent" if dependent else "independent","unknown_dependency":etype=="possible_dependency","counts_as_independent_corroboration":not dependent}); deps.append(r)

narr=[]
for n,headline,segment,desc,typ in [("001","I balneari hanno vinto","La Corte mantiene verifiche e condizioni; il titolo presenta un esito di parte generale.","Esito condizionato trasformato in vittoria complessiva.","framing"),("002","La strada delle gare è obbligata","L'obbligo dell'articolo 12 dipende dalla scarsità; la legge italiana fissa procedure.","Condizione e disciplina nazionale compresse in inevitabilità universale.","context_loss"),("003","Gare solo dove le spiagge sono scarse","La scarsità riguarda autorizzazioni e risorse economicamente disponibili, valutate con criteri qualificati.","Formula vicina alla norma ma omette autorità, metodo e controllo giudiziario.","omission"),("004","Nessun obbligo di gare","La Corte vieta rinnovi ed estensioni automatiche e impone selezione se ricorre scarsità.","La condizione non accertata viene trasformata in assenza generale dell'obbligo.","certainty_change")]:
 i=f"IW-003-NAR-{n}"; r=common(i,["IW-003-SRC-001","IW-003-SRC-010"]); r.update({"comparison_id":i,"event_id":"IW-003-E005","source_document_id":"IW-003-SRC-001","compared_document_ids":["IW-003-SRC-010"],"headline":headline,"lead":segment,"claims_included":["IW-003-CLM-001"],"claims_omitted":["IW-003-CLM-007","IW-003-CLM-008"],"actor_labels":[],"agency_assignment":[],"certainty_markers":["davvero","obbligata","nessun"],"evaluative_language":[],"quotation_changes":[],"quantifier_changes":[],"modality_changes":[desc],"temporal_generalization":[],"context_loss":[desc],"headline_body_divergence":[],"observable_transformations":[{"type":typ,"source_segment":segment,"compared_segment":headline,"description":desc}],"analyst_notes":["Descrizione della trasformazione; nessuna inferenza sull'intenzione o etichetta di propaganda."]}); narr.append(r)

cons=[]
for n,a,b,inc in [("001","IW-003-CLM-001","IW-003-CLM-004","Il claim di eliminazione generale è incompatibile con l'obbligo condizionato conservato dalla Corte."),("002","IW-003-CLM-009","IW-003-CLM-005","L'esclusione dei titoli pre-2009 dopo proroga è incompatibile con il punto 2 del dispositivo.")]:
 i=f"IW-003-CON-{n}"; r=common(i,[a,b]); r.update({"contradiction_id":i,"claim_a":a,"claim_b":b,"subject":"regime delle concessioni balneari","predicate":"applicabilità e selezione","object":"effetti dell'ordinanza C-574/25","definition":"Proposizioni allineate per Italia e cut-off.","temporal_scope":{"start":"2026-07-10T00:00:00Z","end":CUT},"place":"Italia/UE","qualifiers":["scope giuridico"],"incompatibility":inc,"extent":"total","definition_divergence_possible":False,"resolution_evidence_needed":["Nuova decisione o modifica normativa materialmente pertinente"]}); cons.append(r)

wf=common("IW-003-WF-001",["IW-003"]); wf.update({"workflow_id":"IW-003-WF-001","record_id":"IW-003","current_state":"published","history":[{"from":None,"to":"draft","at":NOW,"actor":"Cognitive Logic IW author assisted by Codex","role":"author","reason":"Preparati record, articolo e dossier locali."},{"from":"draft","to":"in_review","at":NOW,"actor":"Cognitive Logic IW author assisted by Codex","role":"author","reason":"Sottoposto al gate umano; nessuna autorizzazione automatica."},{"from":"in_review","to":"approved","at":APPROVED,"actor":"Cognitive Logic designated human publication authority","role":"human publication authority","reason":"Approvazione metodologica esplicita ricevuta: APPROVO IW-003 E AUTORIZZO LA PUBBLICAZIONE."},{"from":"approved","to":"published","at":APPROVED,"actor":"Cognitive Logic designated human publication authority","role":"human publication authority","reason":"Pubblicazione autorizzata esplicitamente dopo validazione con zero errori e zero avvisi."}],"author":"Cognitive Logic IW author assisted by Codex","human_reviewer":REVIEWER,"publication_automatic":False,"reopen_conditions":["nuova prova materiale","modifica normativa","decisione nazionale sulla scarsità","correzione o ritiro fonte"],"new_evidence_policy":"Riaprire la revisione e versionare ogni record interessato.","correction_policy":"Correzioni materiali generano una nuova versione; ogni nuova pubblicazione richiede autorizzazione umana esplicita."})

bundles={"event-registry":events,"claim-registry":clm_records,"source-registry":src_records,"evidence-ledger":ev_records,"source-dependency":deps,"narrative-comparison":narr,"epistemic-assessment":asm_records,"contradictions":cons,"workflow":[wf]}
OUT.mkdir(parents=True,exist_ok=True)
for name,records in bundles.items(): (OUT/f"{name}.json").write_text(json.dumps({"schema_version":"1.0.0","case_id":"IW-003","records":records},ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
manifest={"case_id":"IW-003","title":"Bolkestein e spiagge: la Corte UE ha davvero eliminato l'obbligo delle gare?","schema_version":"1.0.0","record_version":"1.0.0","status":"published","approved_at":APPROVED,"published_at":APPROVED,"reviewer":REVIEWER,"review_mode":"Revisione tecnica e metodologica assistita da Codex con approvazione umana esplicita","final_approval_reserved_to":"Responsabile umano di Cognitive Logic","organizational_independence":False,"external_certification":False,"specialist_legal_review":False,"personal_reviewer_or_signature":None,"approval_scope":"Approvazione metodologica e autorizzazione alla pubblicazione concesse esplicitamente.","cut_off":CUT,"publication_allowed":True,"article_url":"https://cognitivelogic.it/international-watch/bolkestein-spiagge-corte-ue-gare/","dossier_url":"https://cognitivelogic.it/international-watch/iw-003-bolkestein-concessioni-balneari/","public_epistemic_outcome":"PARZIALMENTE VERIFICATA","files":[f"{x}.json" for x in bundles]+["dossier-manifest.json"],"source_count":len(src_records),"claim_count":len(clm_records),"local_evidence_files":[],"missing_local_file_reason":"Nessuna copia protetta archiviata; URL, timestamp e note probatorie delimitate conservati.","methodological_note":"Il claim categorico è CONTRADDETTO. L'esito pubblico composto resta parziale perché l'ordinanza chiarisce condizioni e competenze senza accertare la non scarsità italiana.","revision_warning":"Nuove decisioni, norme o accertamenti territoriali possono modificare il dossier."}
(OUT/"dossier-manifest.json").write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
